version: '3.4'

services:
    catalogdb:
        container_name: catalog-db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=CatalogDb
        ports:
          - "5432:5432"
        volumes:
          - postgres_catalog:/var/lib/postgresql/data/
