version: '3.4'

services:
    catalogdb:
        container_name: CatalogDb
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=CatalogDb
        restart: unless-stopped
        ports:
          - "5432:5432"
        volumes:
          - catalogdb:/var/lib/postgresql/data/
    
    basketdb:
        container_name: BasketDb
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=BasketDb
        restart: unless-stopped
        ports:
          - "5433:5432"
        volumes:
          - basketdb:/var/lib/postgresql/data/
    
    distributedcache:
        container_name: distributedcache
        image: redis
        restart: unless-stopped
        ports:
          - "6380:6379"

    catalog.api:
        container_name: CatalogApi
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ConnectionStrings__dbcnt=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true;
        ports:
            - "6000:8080"
            - "6060:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            - catalogdb

    basket.api:
        container_name: BasketApi
        restart: unless-stopped
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ConnectionStrings__BasketDb=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true;
            - ConnectionStrings__Redis=distributedcache:6379
        ports:
            - "6001:8080"
            - "6061:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            - basketdb
            - distributedcache
    
